[package]
authors = ["Pascal Hertleif <killercup@gmail.com>"]
name = "english-lint"
version = "0.1.0"
license = "MIT/Apache-2.0"
repository = "https://github.com/killercup/english-lint"

[dependencies]
aho-corasick = "0.5.1"
